export {
  getPartnerDashboard as getDashboard,
  getPartnerBookings as getBookings,
  updateBookingStatus,
  getPartnerStos as getStos,
  getPartnerServices as getServices,
  getPartnerCatalogServices as getCatalogServices,
  addPartnerService as addService,
  updatePartnerService as updateService,
  deletePartnerService as deleteService,
  updatePartnerServices as putServices,
  getPartnerAnalytics as getAnalytics,
  getPartnerAnalyticsRange as getAnalyticsRange,
  getPartnerProfile as getProfile,
  updatePartnerProfile as updateProfile,
  uploadProfilePhoto,
} from "./partner";
export type {
  PartnerDashboard as PartnerDashboardData,
  PartnerBooking,
  PartnerBookingClient,
  PartnerServiceItem,
  PartnerCatalogItem,
  PartnerStoItem,
  PartnerAnalytics,
  AnalyticsRangePoint,
  PartnerAnalyticsFull,
  PartnerProfile,
  PartnerProfileUpdate,
} from "./partner";
